/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_yxcoding_ffmpeg_FFmpegUtil */

#ifndef _Included_net_yxcoding_ffmpeg_FFmpegUtil
#define _Included_net_yxcoding_ffmpeg_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_yxcoding_ffmpeg_FFmpegUtil
 * Method:    ffmpegInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_yxcoding_ffmpeg_FFmpegUtil_ffmpegInfo
  (JNIEnv *, jclass);

/*
 * Class:     net_yxcoding_ffmpeg_FFmpegUtil
 * Method:    setCurlDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_yxcoding_ffmpeg_FFmpegUtil_setCurlDebug
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
